/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dust_persondemo_utils_JNIUtils */

#ifndef _Included_com_example_dust_persondemo_utils_JNIUtils
#define _Included_com_example_dust_persondemo_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dust_persondemo_utils_JNIUtils
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_dust_persondemo_utils_JNIUtils_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
